CREATE TABLE MUSICIAN(
SSN VARCHAR(255) NOT NULL PRIMARY KEY,
"Name" VARCHAR(255),
"Address" VARCHAR(255),
Phone_Number VARCHAR(255)); 

CREATE TABLE ALBUM(
ID INT NOT NULL PRIMARY KEY,
Title VARCHAR(255),
Copyright_Date VARCHAR(255),
"Format" VARCHAR(255), -- CD or MC 
Album_Identifier VARCHAR(255),
Producer_SSN VARCHAR(255) NOT NULL,
FOREIGN KEY(Producer_SSN) REFERENCES MUSICIAN(SSN));

CREATE TABLE SONG(
TITLE VARCHAR(255) NOT NULL PRIMARY KEY,
AUTHOR VARCHAR(255),
Album_ID INT NOT NULL, 
FOREIGN KEY (Album_ID) REFERENCES ALBUM(ID));

CREATE TABLE INSTRUMENT(
ID INT NOT NULL PRIMARY KEY, 
NAME VARCHAR(255), 
MUSICAL_KEY VARCHAR(255));

CREATE TABLE PLAYS(
SSN VARCHAR(255) NOT NULL, 
INSTRUMENT_ID INT NOT NULL, 
FOREIGN KEY(SSN) REFERENCES MUSICIAN(SSN),
FOREIGN KEY(INSTRUMENT_ID) REFERENCES INSTRUMENT(ID));

CREATE TABLE PERFORMS(
SSN VARCHAR(255) NOT NULL, 
SONG_TITLE VARCHAR(255) NOT NULL, 
FOREIGN KEY (SSN) REFERENCES MUSICIAN(SSN),
FOREIGN KEY (SONG_TITLE) REFERENCES SONG(TITLE));


